<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            [
                Customer::name => 'Max Mustermann',
                Customer::is_company => true,
                Customer::company_name => 'Mustermann GmbH',
                Customer::email => 'max.mustermann@mustermann-gmbh.de',
                Customer::phone => '+49 30 12345678',
                Customer::street => 'Musterstraße',
                Customer::street_nr => '123',
                Customer::zip => '10115',
                Customer::city => 'Berlin',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'Langjähriger Kunde, zahlt immer pünktlich.',
            ],
            [
                Customer::name => 'Anna Schmidt',
                Customer::is_company => true,
                Customer::company_name => 'Schmidt Sport Marketing',
                Customer::email => 'anna.schmidt@schmidt-marketing.de',
                Customer::phone => '+49 40 98765432',
                Customer::street => 'Alsterweg',
                Customer::street_nr => '45',
                Customer::zip => '20099',
                Customer::city => 'Hamburg',
                Customer::payment_method => 'Lastschrift',
                Customer::notes => 'Interessiert an Premium-Positionen.',
            ],
            [
                Customer::name => 'Thomas Müller',
                Customer::is_company => true,
                Customer::company_name => 'Müller & Söhne AG',
                Customer::email => 'thomas.mueller@mueller-soehne.de',
                Customer::phone => '+49 89 55544433',
                Customer::street => 'Maximilianstraße',
                Customer::street_nr => '78',
                Customer::zip => '80539',
                Customer::city => 'München',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'VIP-Kunde, bevorzugt Stadion-Positionen.',
            ],
            [
                Customer::name => 'Sarah Weber',
                Customer::is_company => true,
                Customer::company_name => 'Weber Sportswear',
                Customer::email => 'sarah.weber@weber-sportswear.de',
                Customer::phone => '+49 211 77788899',
                Customer::street => 'Königsallee',
                Customer::street_nr => '100',
                Customer::zip => '40212',
                Customer::city => 'Düsseldorf',
                Customer::payment_method => 'Kreditkarte',
                Customer::notes => 'Neue Kundin, sehr engagiert.',
            ],
            [
                Customer::name => 'Michael Becker',
                Customer::is_company => false,
                Customer::company_name => null,
                Customer::email => 'michael.becker@email.de',
                Customer::phone => '+49 351 22233344',
                Customer::street => 'Prager Straße',
                Customer::street_nr => '20',
                Customer::zip => '01069',
                Customer::city => 'Dresden',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'Privatperson, kleines Budget.',
            ],
            [
                Customer::name => 'Julia Fischer',
                Customer::is_company => true,
                Customer::company_name => 'Fischer Consulting',
                Customer::email => 'julia.fischer@fischer-consulting.de',
                Customer::phone => '+49 30 66677788',
                Customer::street => 'Friedrichstraße',
                Customer::street_nr => '200',
                Customer::zip => '10117',
                Customer::city => 'Berlin',
                Customer::payment_method => 'Lastschrift',
                Customer::notes => 'Mehrere Felder gebucht.',
            ],
            [
                Customer::name => 'Peter Hoffmann',
                Customer::is_company => true,
                Customer::company_name => 'Hoffmann Automobil GmbH',
                Customer::email => 'p.hoffmann@hoffmann-auto.de',
                Customer::phone => '+49 40 33344455',
                Customer::street => 'Hafenstraße',
                Customer::street_nr => '67',
                Customer::zip => '20359',
                Customer::city => 'Hamburg',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'Möchte langfristige Partnerschaft.',
            ],
            [
                Customer::name => 'Lisa Schneider',
                Customer::is_company => true,
                Customer::company_name => 'Schneider Fitness Center',
                Customer::email => 'lisa.schneider@schneider-fitness.de',
                Customer::phone => '+49 89 11122233',
                Customer::street => 'Sendlinger Straße',
                Customer::street_nr => '45',
                Customer::zip => '80331',
                Customer::city => 'München',
                Customer::payment_method => 'Lastschrift',
                Customer::notes => 'Interessiert an Trainingsfeldern.',
            ],
            [
                Customer::name => 'Daniel Koch',
                Customer::is_company => true,
                Customer::company_name => 'Koch Immobilien',
                Customer::email => 'daniel.koch@koch-immobilien.de',
                Customer::phone => '+49 211 99988877',
                Customer::street => 'Schadowstraße',
                Customer::street_nr => '88',
                Customer::zip => '40212',
                Customer::city => 'Düsseldorf',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'Bevorzugt zentrale Positionen.',
            ],
            [
                Customer::name => 'Sabine Wagner',
                Customer::is_company => true,
                Customer::company_name => 'Wagner Events',
                Customer::email => 'sabine.wagner@wagner-events.de',
                Customer::phone => '+49 351 44455566',
                Customer::street => 'Altmarkt',
                Customer::street_nr => '15',
                Customer::zip => '01067',
                Customer::city => 'Dresden',
                Customer::payment_method => 'Kreditkarte',
                Customer::notes => 'Organisiert Sportveranstaltungen.',
            ],
            [
                Customer::name => 'Frank Zimmermann',
                Customer::is_company => true,
                Customer::company_name => 'Zimmermann Tech Solutions',
                Customer::email => 'frank.zimmermann@ztech.de',
                Customer::phone => '+49 30 77766655',
                Customer::street => 'Alexanderplatz',
                Customer::street_nr => '1',
                Customer::zip => '10178',
                Customer::city => 'Berlin',
                Customer::payment_method => 'Überweisung',
                Customer::notes => 'Tech-Firma, sucht moderne Werbeflächen.',
            ],
            [
                Customer::name => 'Claudia Meyer',
                Customer::is_company => false,
                Customer::company_name => null,
                Customer::email => 'claudia.meyer@email.de',
                Customer::phone => '+49 40 55566677',
                Customer::street => 'Reeperbahn',
                Customer::street_nr => '150',
                Customer::zip => '20359',
                Customer::city => 'Hamburg',
                Customer::payment_method => 'Lastschrift',
                Customer::notes => 'Stammkundin seit 2 Jahren.',
            ],
        ];

        foreach ($customers as $customerData) {
            Customer::create($customerData);
        }
    }
}
